name: Build and Deploy to Deployment Branch

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Prepare deployment artifacts
        run: |
          mkdir deploy_dist
          cp wsgi.py deploy_dist/
          cp app.py deploy_dist/
          cp -r app/ deploy_dist/
          cp requirements.txt deploy_dist/
          cp .python-version deploy_dist/

      - name: Deploy to 'deployment' branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deployment
          publish_dir: ./deploy_dist
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
